server_name = "iot-server"
bind_address = "0.0.0.0:9992"

[router]
router_id = 1
router_server_addr = "0.0.0.0:50002"
keep_alive_timeout = 30

[raft]
node_id = 2
raft_network_addr = "0.0.0.0:9092"
heartbeat_interval = 500
election_timeout_min = 1500
election_timeout_max = 3000

#[redis]
#redis_connection = "redis://default:password@127.0.0.1:6379"